### ISSUE TITLE
Ember-inputmask bad version v0.3.0

### ISSUE THREAD

**Issue by cah-briangantzler** [wearemolecule/date-range-picker#202]
https://github.com/pzuraq/ember-inputmask

The below comment is on the page 

In case you are using v0.3.0 of this addon -- it was a versioning mistake. In fact, v0.3.0 is older than v0.2.1 and we don't recommend it. Feel free to upgrade to the latest version of either v0.2.x or v0.4.x.

Would love for you to support the v0.4.x series

**Comment by osxi** [comment]
@cah-briangantzler Thanks for the heads up! I remember seeing that but don't remember why I used v0.3.0. I'll try out 0.4.x and see how it goes.

**Comment by cah-briangantzler** [comment]
I am strongly looking at using this addon. Currently I have no bower in my application at all, switching to 0.4.x will allow me to keep bower free :)

**Comment by osxi** [comment]
@cah-briangantzler Hearing that actually makes me pretty excited. After I finish https://github.com/wearemolecule/date-range-picker/pull/203, which bumps the ember-inputmask version to v0.4.x and removes the lone bower vestige, we should be good to go there. That also brings our product one step closer to being Bower-free.
